set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" vundle
Bundle 'gmarik/vundle'
" bundles
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'tomtom/tlib_vim'
Bundle 'garbas/vim-snipmate'
Bundle 'honza/vim-snippets'
Bundle 'bling/vim-airline'
Bundle 'kien/ctrlp.vim'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/nerdtree'
Bundle 'myusuf3/numbers.vim'
Bundle 'tpope/vim-surround'
"Bundle 'joonty/vim-phpqa'
Bundle 'flazz/vim-colorschemes'
Bundle 'tobyS/pdv'
Bundle 'tobyS/vmustache'

filetype plugin indent on

syntax on

let mapleader = ","

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set colorcolumn=80
set encoding=utf-8
set scrolloff=3
set laststatus=2
set autoindent
set showmode
set showcmd
set number
set mouse=a
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set undofile

set undodir=~/.vim/tmp/undo//
set backupdir=~/.vim/tmp/backup//
set directory=~/.vim/tmp/swap//
set backup
set noswapfile

set hlsearch
set incsearch
set ignorecase
set smartcase
set gdefault
set showmatch

nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

set wrap
set textwidth=79
set formatoptions=qrn1
set list
set listchars=tab:▸\ ,eol:¬

nnoremap <leader>w <C-w>v<C-w>l
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>es :split $MYVIMRC<cr>

inoremap <F4> <esc>:NERDTreeToggle<cr>
noremap <F4> :NERDTreeToggle<cr>

"noremap <Up> <nop>
"noremap <Down> <nop>
"noremap <Left> <nop>
"noremap <Right> <nop>
"inoremap <Up> <nop>
"inoremap <Down> <nop>
"inoremap <Left> <nop>
"inoremap <Right> <nop>

inoremap jj <esc>
xnoremap <silent> <C-c> "zy:call system('loliclip -ci', @z)<cr>

" Configure PDV
let g:pdv_template_dir = $HOME . "/.vim/bundle/pdv/templates"
nnoremap <leader>p :call pdv#DocumentCurrentLine()<CR>

colorscheme badwolf
