set nocompatible
filetype off
syntax on

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

"Bundle 'drmingdrmer/xptemplate.git'
Bundle 'tpope/vim-surround.git'
Bundle 'tpope/vim-rails.git'
Bundle 'tpope/vim-ragtag.git'
Bundle 'scrooloose/nerdtree.git'
Bundle 'scrooloose/nerdcommenter.git'
"Bundle 'groenewege/vim-less.git'
Bundle 'mileszs/ack.vim.git'
Bundle 'kien/ctrlp.vim.git'
Bundle 'myusuf3/numbers.vim.git'
Bundle 'Lokaltog/vim-powerline.git'
"Bundle 'sjl/gundo.vim.git'
Bundle 'gregsexton/MatchTag.git'

" dependencies vim-snipmate
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle "snipmate-snippets"
" vim-snipmate
Bundle 'garbas/vim-snipmate.git'

filetype plugin indent on

let mapleader = ","

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set encoding=utf-8
set scrolloff=3
set laststatus=2
set autoindent
set showmode
set showcmd
set number
set mouse=a
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set undofile

" searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set gdefault
set showmatch

" wildmenu 
set wildmenu
set wildmode=list:longest
set wildignore+=.hg,.git,.svn                    " Version control
set wildignore+=*.aux,*.out,*.toc                " LaTeX intermediate files
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg   " binary images
set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest " compiled object files
set wildignore+=*.spl                            " compiled spelling word lists
set wildignore+=*.sw?                            " Vim swap files
set wildignore+=*.DS_Store                       " OSX bullshit

set wildignore+=*.luac                           " Lua byte code

set wildignore+=migrations                       " Django migrations
set wildignore+=*.pyc                            " Python byte code

set wildignore+=*.orig 

" Backups
set undodir=~/.vim/tmp/undo//     " undo files
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set backup                        " enable backups
set noswapfile                    " It's 2012, Vim.

" clear search
nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=85
set list
set listchars=tab:▸\ ,eol:¬

" split window and focus
nnoremap <leader>w <C-w>v<C-w>l
" split window movement
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>es :split $MYVIMRC<cr>

noremap <F4> :NERDTreeToggle<cr>
inoremap <F4> <esc>:NERDTreeToggle<cr>

let NERDTreeHighlightCursorline = 1
let NERDTreeIgnore = ['.vim$', '\~$', '.*\.pyc$', 'whoosh_index', '.*.pid', 
                     \'.*-fixtures-.*.json', '.*\.o$', 'db.db', 'tags.bak']

"nnoremap <F5> :GundoToggle<cr>
"inoremap <F5> <esc>:GundoToggle<cr>

"" Colors
colorscheme badwolf


"let g:Powerline_symbols = 'fancy'
