#!/bin/sh

#xrandr --output DVI-D-0 --mode 1280x1024 --pos 0x0 --rotate normal --output HDMI-0 --off --output DVI-I-1 --primary --mode 1920x1200 --pos 1280x0 --rotate normal &
# Set main screen as primary
#xrandr --output DVI-I-1 --primary &
#xrandr --output DVI-I-1 --mode 1920x1200 --pos 3840x0 --rotate left --output DP-1 --primary --mode 3840x2160 --pos 0x0 --rotate normal --dpi 144 &
#xrandr --output DP-1 --primary --mode 3840x2160 --pos 0x0 --rotate normal --dpi 144 &

sh ~/.screenlayout/qwe.sh &
#setxkbmap -option caps:escape
#xsetroot -cursor_name left_ptr
#xset m 1 0
compton &
#clipmenud &
#dropbox &
dunst &
#trayer --edge top --align right --widthtype pixel --width 195 --heighttype pixel --height 14 --SetPartialStrut false --expand true --transparent true --alpha 0 --tint 0x151515 --monitor primary &
#pasystray &
nitrogen --restore &
(sleep 2 && redshift -l 57.69:11.98 -t 6500:4300 -g 0.8 -m vidmode -v) &
pasystray &
#ssh-agent xmonad
ssh-agent i3
